import { View } from "react-native";

// Client/constants/Texts.js
export const Texts = {
  en: {
    Language: "Language",
    ChangeLanguage: "Change language",
    BusyMode: "Busy Mode",
    EndBusyMode: "End Busy Mode",
    ProfileSettings: "Profile Settings",
    LogOut: "Log Out",
    AddContactStarted: "Add a contact to get started!",
    AddGroupStarted: "Join a group to get started!",
    Contacts: "Contacts",
    Groups: "Groups",
    RandomZalk: "Random Zalk",
    AddContacts: "Add Contacts",
    AddContactsInput: "Search for username",
    AddGroups: "Add Groups",
    AddGroupsInput: "Search for group name",
    NoNotifications: "You don't have any notifications",
    Login: "Login",
    SignUp: "Sign Up",
    SignUpTitle: "Sign Up",
    SignIn: "Sign in",
    SignInTitle: "Sign In",
    Username: "Username",
    Password: "Password",
    Email: "Email",
    ConfirmPassword: "Confirm Password",
    ForgotPassword: "Forgot password?",
    DontHaveAccount: "Don't have an account? Sign up",
    AlreadyHaveAccount: "Already have an account? Sign in",
    PasswordsDontMatch: "Passwords don't match",
    Passwords8Characters: "Password must be at least 8 characters long",
    EmailExists: "Email is already associated with another account",
    UsernameExists: "Username already exists",
    RegistrationFailed: "Registration failed",
    RegistrationFailedTryAgain: "Registration failed, please try again",
    InvalidEmail: "Please enter a valid email address.",
    EnterBothUserPass: "Please enter both your username and password.",
    IncorrectUserPass: "Incorrect username or password",
    EmptyUsername: "Please enter a username",
    EmptyPassword: "Please enter a password",
    EmptyEmail: "Please enter an email address",
    Notifications: "Notifications",
    Settings: "Settings",
    Info: "Information",
    info: "information",
    username: "username",
    password: "password",
    email: "email",
    ChangeYour: "Change your",
    EnterNewa: "Enter your new",
    EnterNewo: "Enter your new",
    Change: "Change",
    TapRandomZalk: "Tap to Random Zalk",
    Anonymous: "Anonymous",
    and: "and",
    RZmodalFirstPar: "way to connect with other users.",
    TapStart: "Tap Start",
    RZToSearch: "to begin your search for a partner.",
    RZThreeMin: "3 minutes",
    RZConnect: "of automatic connection if two users connect.",
    RZReady: "Are you ready for a random Zalk?",
    RZStartButton: "Start",
    RZCancelButton: "Not yet",
    RZSearchingCon: "Searching for a connection...",
    ProfilePhoto: "Profile Photo",
    DeleteGroup: "Delete Group",
    ViewGroup: "View Group",
    DeleteContact: "Delete Contact",
    ViewContact: "View Contact",
    TapToChat: "Tap to chat",
    TapForDetails: "Tap for details",
    SentRequest: "Sent you a request",
    RZEndButton: "End connection",
    RZConnectedWith: "Connected with:",
    RZConnected: "Connection established!",
    LeaveGroupConfirm: "Leaving the group",
    UnfriendContactConfirm: "Removing from contacts",
    Cancel : "Cancel",
    Confirm : "Confirm",
    FriendRequest : "Friend Request",
    From : "From",
    Accept : "Accept",
    Decline : "Decline",
    TapToDetails: "Tap to see details",
  },
  es: {
    Language: "Idioma",
    ChangeLanguage: "Cambiar idioma",
    BusyMode: "Modo ocupado",
    EndBusyMode: "Quitar modo ocupado",
    ProfileSettings: "Ajustes de perfil",
    LogOut: "Cerrar sesión",
    AddContactStarted: "Añade un contacto para comenzar!",
    AddGroupStarted: "Entra en un grupo para comenzar!",
    Contacts: "Contactos",
    Groups: "Grupos",
    RandomZalk: "Zalk Aleatorio",
    AddContacts: "Añadir Contactos",
    AddContactsInput: "Buscar por nombre de usuario",
    AddGroups: "Añadir Grupos",
    AddGroupsInput: "Buscar por nombre de grupo",
    NoNotifications: "No tienes notificaciones",
    Login: "Iniciar sesión",
    SignUpTitle: "Registro",
    SignUp: "Registrarse",
    SignIn: "Iniciar sesión",
    SignInTitle: "Inicio de sesión",
    Username: "Nombre de usuario",
    Password: "Contraseña",
    Email: "Correo electrónico",
    ConfirmPassword: "Confirmar contraseña",
    ForgotPassword: "¿Olvidaste la contraseña?",
    DontHaveAccount: "¿No tienes una cuenta? Regístrate",
    AlreadyHaveAccount: "¿Ya tienes una cuenta? Inicia sesión",
    PasswordsDontMatch: "Las contraseñas no coinciden",
    Passwords8Characters: "La contraseña debe tener al menos 8 caracteres",
    EmailExists: "El correo ya está asociado a otra cuenta",
    UsernameExists: "El nombre de usuario ya existe",
    RegistrationFailed: "Error al registrarse",
    RegistrationFailedTryAgain: "Error al registrarse, inténtalo de nuevo",
    InvalidEmail: "Introduce una dirección de correo válida.",
    EnterBothUserPass: "Por favor, introduce ambos, usuario y contraseña.",
    IncorrectUserPass: "Nombre de usuario o contraseña incorrectos",
    EmptyUsername: "Por favor, introduce un nombre de usuario",
    EmptyPassword: "Por favor, introduce una contraseña",
    EmptyEmail: "Por favor, introduce una dirección de correo electrónico",
    Notifications: "Notificaciones",
    Settings: "Ajustes",
    Info: "Información",
    info: "información",
    username: "nombre de usuario",
    password: "contraseña",
    email: "correo electrónico",
    ChangeYour: "Cambia tu",
    EnterNewa: "Introduce tu nueva",
    EnterNewo: "Introduce tu nuevo",
    Change: "Cambiar",
    TapRandomZalk: "Zalk Aleatorio",
    Anonymous: "Anónimo",
    and: "y",
    temporary: "temporal",
    RZmodalFirstPar: ", conectarás con otros usuarios.",
    TapStart: "Pulsa comenzar",
    RZToSearch: "para comenzar a buscar una conexión.",
    ThreeMin: "3 minutos",
    RZConnect: "de conexión automática si dos usuarios se conectan.",
    RZReady: "¿Estás listo para un Zalk aleatorio?",
    RZStartButton: "Comenzar",
    RZCancelButton: "Aún no",
    RZSearchingCon: "Buscando una conexión...",
    ProfilePhoto: "Foto de perfil",
    DeleteGroup: "Salir del Grupo",
    ViewGroup: "Ver Grupo",
    DeleteContact: "Eliminar Contacto",
    ViewContact: "Ver Contacto",
    TapToChat: "Toca para entrar al chat",
    TapForDetails: "Toca para ver detalles",
    SentRequest: "Te ha enviado una solicitud",
    RZEndButton: "Terminar conexión",
    RZConnectedWith: "Conectado con:",
    RZConnected: "Conexión establecida!",
    LeaveGroupConfirm: "Salir del grupo",
    UnfriendContactConfirm: "Eliminar de contactos",
    Cancel : "Cancelar",
    Confirm : "Confirmar",
    FriendRequest : "Solicitud de amistad",
    From : "De",
    Accept : "Aceptar",
    Decline : "Rechazar",
    TapToDetails: "Toca para ver detalles",
  },
};